import type {
  UserDTO,
  PlaceDTO,
  CourseDTO,
  ClassDTO,
  VacancyDTO,
  InterviewDTO,
  StudentDTO,
  ShiftDTO,
  NotificationTimelineDTO,
  TransferRequestDTO,
} from "@/types";

export const mockUsers: UserDTO[] = [
  {
    id: "usr-1",
    name: "Ana Silva",
    email: "ana.silva@weg.net",
    role: "ADMIN",
    active: true,
  },
  {
    id: "usr-2",
    name: "Carlos Eduardo",
    email: "carlos.eduardo@weg.net",
    role: "COORDINATOR",
    active: true,
  },
  {
    id: "usr-3",
    name: "Mariana Costa",
    email: "mariana.costa@weg.net",
    role: "MANAGER",
    active: true,
  },
  {
    id: "usr-4",
    name: "Lucas Oliveira",
    email: "lucas.oliveira@weg.net",
    role: "STUDENT",
    active: true,
  },
  {
    id: "usr-5",
    name: "Fernanda Souza",
    email: "fernanda.souza@weg.net",
    role: "COORDINATOR",
    active: false,
  },
];

export const mockPlaces: PlaceDTO[] = [
  {
    id: "plc-1",
    name: "Unidade Fabril 1 - Jaraguá do Sul",
    code: "UF-01",
    description: "Planta principal de motores de alta tensão",
    city: "Jaraguá do Sul",
    state: "SC",
    status: "ACTIVE",
  },
  {
    id: "plc-2",
    name: "Unidade Fabril 2 - Guaramirim",
    code: "UF-02",
    description: "Planta de componentes eletroeletrônicos",
    city: "Guaramirim",
    state: "SC",
    status: "ACTIVE",
  },
  {
    id: "plc-3",
    name: "Centro de Treinamento Técnico",
    code: "CTT-01",
    description: "Laboratórios e salas de aula práticas",
    city: "Jaraguá do Sul",
    state: "SC",
    status: "ACTIVE",
  },
];

export const mockCourses: CourseDTO[] = [
  {
    id: "crs-1",
    name: "Técnico em Eletromecânica",
    code: "TEL-2024",
    coordinatorName: "Carlos Eduardo",
    totalStudents: 48,
    status: "ACTIVE",
  },
  {
    id: "crs-2",
    name: "Automação Industrial",
    code: "AUT-2024",
    coordinatorName: "Carlos Eduardo",
    totalStudents: 36,
    status: "ACTIVE",
  },
  {
    id: "crs-3",
    name: "Usinagem CNC",
    code: "CNC-2024",
    coordinatorName: "Fernanda Souza",
    totalStudents: 24,
    status: "COMPLETED",
  },
];

export const mockClasses: ClassDTO[] = [
  {
    id: "cls-1",
    name: "Turma A - Eletromecânica",
    code: "TEL-A",
    courseName: "Técnico em Eletromecânica",
    period: "Matutino",
    totalStudents: 24,
    maxStudents: 25,
    status: "IN_PROGRESS",
  },
  {
    id: "cls-2",
    name: "Turma B - Eletromecânica",
    code: "TEL-B",
    courseName: "Técnico em Eletromecânica",
    period: "Vespertino",
    totalStudents: 24,
    maxStudents: 25,
    status: "IN_PROGRESS",
  },
  {
    id: "cls-3",
    name: "Turma A - Automação",
    code: "AUT-A",
    courseName: "Automação Industrial",
    period: "Noturno",
    totalStudents: 36,
    maxStudents: 40,
    status: "PLANNED",
  },
];

export const mockVacancies: VacancyDTO[] = [
  {
    id: "vac-1",
    title: "Aprendiz de Montagem Elétrica",
    department: "Produção de Motores",
    location: "Unidade Fabril 1",
    totalSpots: 10,
    filledSpots: 8,
    status: "OPEN",
  },
  {
    id: "vac-2",
    title: "Técnico em Manutenção Preventiva",
    department: "Manutenção Geral",
    location: "Unidade Fabril 2",
    totalSpots: 5,
    filledSpots: 5,
    status: "CLOSED",
  },
  {
    id: "vac-3",
    title: "Operador CNC Aprendiz",
    department: "Usinagem",
    location: "Unidade Fabril 1",
    totalSpots: 4,
    filledSpots: 1,
    status: "URGENT",
  },
];

export const mockInterviews: InterviewDTO[] = [
  {
    id: "int-1",
    candidateName: "Gabriel Santos",
    candidateEmail: "gabriel.santos@email.com",
    vacancyTitle: "Aprendiz de Montagem Elétrica",
    scheduledDate: "2026-07-25",
    scheduledTime: "09:00",
    interviewerName: "Mariana Costa",
    status: "SCHEDULED",
  },
  {
    id: "int-2",
    candidateName: "Beatriz Lima",
    candidateEmail: "beatriz.lima@email.com",
    vacancyTitle: "Operador CNC Aprendiz",
    scheduledDate: "2026-07-24",
    scheduledTime: "14:30",
    interviewerName: "Carlos Eduardo",
    status: "APPROVED",
  },
  {
    id: "int-3",
    candidateName: "Matheus Rocha",
    candidateEmail: "matheus.rocha@email.com",
    vacancyTitle: "Técnico em Manutenção Preventiva",
    scheduledDate: "2026-07-22",
    scheduledTime: "11:00",
    interviewerName: "Mariana Costa",
    status: "REJECTED",
  },
];

export const mockStudents: StudentDTO[] = [
  {
    id: "std-1",
    name: "Lucas Silva Santos",
    registration: "2024001",
    email: "lucas.santos@estudante.weg.net",
    courseName: "Técnico em Eletromecânica",
    className: "Turma A - Eletromecânica",
    shift: "Turno A (06:00 - 14:00)",
    status: "ACTIVE",
    attendanceRate: 96.5,
    performanceGrade: 9.2,
  },
  {
    id: "std-2",
    name: "Juliana Mendes",
    registration: "2024002",
    email: "juliana.mendes@estudante.weg.net",
    courseName: "Automação Industrial",
    className: "Turma A - Automação",
    shift: "Turno B (14:00 - 22:00)",
    status: "TRANSFERRING",
    attendanceRate: 92.0,
    performanceGrade: 8.7,
  },
  {
    id: "std-3",
    name: "Rafael Oliveira",
    registration: "2024003",
    email: "rafael.oliveira@estudante.weg.net",
    courseName: "Técnico em Eletromecânica",
    className: "Turma B - Eletromecânica",
    shift: "Turno A (06:00 - 14:00)",
    status: "ACTIVE",
    attendanceRate: 88.0,
    performanceGrade: 7.9,
  },
];

export const mockShifts: ShiftDTO[] = [
  {
    id: "shf-1",
    name: "Turno A - Matutino",
    code: "TRN-A",
    supervisorName: "Mariana Costa",
    capacity: 50,
    currentOccupancy: 45,
    occupancyPercentage: 90,
    status: "HIGH_DEMAND",
  },
  {
    id: "shf-2",
    name: "Turno B - Vespertino",
    code: "TRN-B",
    supervisorName: "Carlos Eduardo",
    capacity: 50,
    currentOccupancy: 32,
    occupancyPercentage: 64,
    status: "NORMAL",
  },
  {
    id: "shf-3",
    name: "Turno C - Noturno",
    code: "TRN-C",
    supervisorName: "Ana Silva",
    capacity: 30,
    currentOccupancy: 30,
    occupancyPercentage: 100,
    status: "FULL",
  },
];

export const mockTimeline: NotificationTimelineDTO[] = [
  {
    id: "tml-1",
    studentId: "std-1",
    title: "Solicitação de Troca Aprovada",
    description: "Transferência do Turno B para o Turno A autorizada pelo coordenador.",
    date: "22/07/2026 às 14:30",
    type: "TRANSFER",
    status: "success",
  },
  {
    id: "tml-2",
    studentId: "std-1",
    title: "Entrevista de Acompanhamento Agendada",
    description: "Reunião de avaliação de desempenho com a supervisão.",
    date: "18/07/2026 às 09:00",
    type: "INTERVIEW",
    status: "info",
  },
  {
    id: "tml-3",
    studentId: "std-1",
    title: "Alerta de Frequência",
    description: "Frequência no limite mínimo estipulado para o módulo de Automação.",
    date: "10/07/2026 às 16:15",
    type: "WARNING",
    status: "warning",
  },
];

export const mockTransferRequests: TransferRequestDTO[] = [
  {
    id: "req-1",
    studentName: "Juliana Mendes",
    currentShift: "Turno B (14:00 - 22:00)",
    targetShift: "Turno A (06:00 - 14:00)",
    reason: "Compatibilidade de horário com módulo universitário no período noturno",
    requestedAt: "22/07/2026",
    status: "PENDING",
  },
  {
    id: "req-2",
    studentName: "Rafael Oliveira",
    currentShift: "Turno A (06:00 - 14:00)",
    targetShift: "Turno C (22:00 - 06:00)",
    reason: "Motivos pessoais de deslocamento residencial",
    requestedAt: "21/07/2026",
    status: "PENDING",
  },
];
